[07-18 15:18:34]: [INFO] Created column 'regdate' and set the current timestamp, 1689707914046, to all 0 rows
[07-18 15:18:34]: [INFO] SQLite Setup finished
[07-18 15:18:34]: [WARN] Error while hooking into LuckPerms [PermissionHandlerException]: Could not get api of LuckPerms
[07-18 15:18:34]: fr.xephi.authme.permission.handlers.PermissionHandlerException: Could not get api of LuckPerms
	at fr.xephi.authme.permission.handlers.LuckPermsHandler.<init>(LuckPermsHandler.java:43)
	at fr.xephi.authme.permission.PermissionsManager.createPermissionHandler(PermissionsManager.java:135)
	at fr.xephi.authme.permission.PermissionsManager.setup(PermissionsManager.java:92)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.invokeMethod(ReflectionUtils.java:73)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.postProcess(PostConstructMethodInvoker.java:27)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.runPostConstructHandlers(InjectorImpl.java:271)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:247)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:492)
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:406)
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:554)
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:257)
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:928)
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: net.luckperms.api.LuckPermsProvider$NotLoadedException: The LuckPerms API isn't loaded yet!
This could be because:
  a) the LuckPerms plugin is not installed or it failed to enable
  b) the plugin in the stacktrace does not declare a dependency on LuckPerms
  c) the plugin in the stacktrace is retrieving the API before the plugin 'enable' phase
     (call the #get method in onEnable, not the constructor!)

	at net.luckperms.api.LuckPermsProvider.get(LuckPermsProvider.java:53)
	at fr.xephi.authme.permission.handlers.LuckPermsHandler.<init>(LuckPermsHandler.java:41)
	... 29 more

[07-18 15:18:34]: [INFO] Hooked into Vault!
[07-18 15:18:35]: [INFO] Hooked successfully into Multiverse-Core
[07-18 15:18:35]: [INFO] AuthMe 5.6.0-beta2 build n.2453 successfully enabled!
[07-18 15:18:49]: [INFO] Downloading GEO IP database, because the old database is older than 30 days or doesn't exist
[07-18 15:18:49]: [WARN] No MaxMind credentials found in the configuration file! GeoIp protections will be disabled.
[07-18 15:18:49]: [INFO] There is no newer GEO IP database uploaded to MaxMind. Using the old one for now.
[07-18 15:18:49]: [WARN] Could not download GeoLiteAPI database [FileNotFoundException]: plugins\AuthMe\GeoLite2-Country.mmdb (El sistema no puede encontrar el archivo especificado)
[07-18 15:18:49]: java.io.FileNotFoundException: plugins\AuthMe\GeoLite2-Country.mmdb (El sistema no puede encontrar el archivo especificado)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
	at fr.xephi.authme.libs.com.maxmind.db.BufferHolder.<init>(BufferHolder.java:20)
	at fr.xephi.authme.libs.com.maxmind.db.Reader.<init>(Reader.java:121)
	at fr.xephi.authme.service.GeoIpService.startReading(GeoIpService.java:173)
	at fr.xephi.authme.service.GeoIpService.updateDatabase(GeoIpService.java:144)
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81)
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

[07-18 15:29:44]: [INFO] AuthMe 5.6.0-beta2-b2453 disabled!
